# mysql-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: default
type: Opaque
data:
  # Base64 encoded values
  # Example: echo -n "your_root_password" | base64
  mysql-root-password: cm9vdA== # Replace with your actual base64 encoded root password : root
  wordpress-db-user: dXNlcg== # Replace with your actual base64 encoded WordPress DB user: user
  wordpress-db-password: cGFzc3dvcmQ= # Replace with your actual base64 encoded WordPress DB password
  wordpress-db-name: bnNt # Replace with your actual base64 encoded WordPress DB name: nsm
