# mysql-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data/mysql # Make sure this exists on each node or restrict to a node
  persistentVolumeReclaimPolicy: Retain
