apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default 
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.2
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql:3306
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress123
        ports:
        - containerPort: 80
