# wordpress-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate # Ensures only one WordPress pod is running at a time during updates
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest # You can specify a version like wordpress:6.5.4
        ports:
        - containerPort: 80
          name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service # <--- IMPORTANT: This MUST match the name of your MySQL Service (which you should create as 'mysql-service')
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets # Your Secret name for database credentials
              key: wordpress-db-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: wordpress-db-password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: wordpress-db-name
        # Optional: If you want to set the WordPress site URL explicitly (uncomment and adjust if needed)
        # - name: WORDPRESS_URL
        #   value: http://10.5.1.6:30089 # Or your domain name if you use Ingress
